Issue #1068 average well rate timeseries
Deltares/imod-python pull request #1102
Opened 2024-07-08 09:43 UTC by luitjansl

Fixes #1068 

# Description

# Checklist

- [ ] Links to correct issue
- [ ] Update changelog, if changes affect users
- [ ] PR title starts with ``Issue #nr``, e.g. ``Issue #737``
- [ ] Unit tests were added
- [ ] **If feature added**: Added/extended example

2024-07-11 16:39 UTC, JoerivanEngelen reviewed
This my review part 1, stopped at line 94 of expand_repetitions.py; will work on that tomorrow. Submitted now to ensure it is saved and not deleted somewhere.

2024-07-11 16:39 UTC, JoerivanEngelen commented on imod/tests/test_mf6/test_mf6_resampling.py
> +    )
This is more readable, could you try and see if this works? If so, update the other cases in this form? I think this is more readable.

```suggestion
    timeseries = pd.DataFrame(
        {}, columns=["time", "rate", "x", "y", "id", "filt_top", "filt_bot"]
    )
   
    timeseries["time"] = [datetime(1989, 1, i) for i in [1, 3, 4, 5, 6]]
    timeseries["rate"] = [i * 100 for i in range(1, 6)]
    timeseries["x"] = 0
    timeseries["y"] = 0
    timeseries["id"] = "ID"
    timeseries["filt_top"] = 20
    timeseries["filt_bot"] = 10

```

2024-07-11 16:39 UTC, JoerivanEngelen commented on imod/tests/test_mf6/test_mf6_resampling.py
Tests look good, nice test cases. My main comments are the test cases setup being quite verbose. I have a suggestion to reduce that, so we can more easily tell what's what. Furthermore the appropriate place for this file is I think is: ``tests/test_mf6/test_utilities/test_resampling.py``

2024-07-11 16:39 UTC, JoerivanEngelen commented on imod/util/expand_repetitions.py
> +        ] = well_rate["filt_bot"][0]
Getting verbose here, I think this should reduce the amount of code here:

```suggestion
    time_before_start_input = intermediate_df["time"] < well_rate["time"][0]
    if time_before_start_input[0]:
        intermediate_df.loc[time_before_start_input, "rate"] = 0.0
        intermediate_df.loc[time_before_start_input, "x"] = well_rate["x"][0]
        intermediate_df.loc[time_before_start_input, "y"] = well_rate["y"][0]
...
#etc
```

2024-07-12 13:16 UTC, JoerivanEngelen requested changes
I've quite significantly adapted ``imod/util/expand_repetitions.py``, to better utilize pandas functionality to compute the integrals. The unittests for the resampling work now.
Some things that appeared while working on this:

- The tests specify rate as integers, but I think it is more common to have floats. Could you turn them into floats?
- I'm not sure ``resample_timeseries`` are in the right place now as this is namespace is used for quite generic utilities, used throughout different modules. ``Resample_timeseries`` on the other hand is quite specific to resampling a single well. Perhaps a better place for this is: ``imod/mf6/utilities/resampling/wells.py``
- Could you improve the setup of the test cases with what I mentioned?

2024-07-12 14:13 UTC, luitjansl commented on imod/util/expand_repetitions.py
> +    intermediate_df.insert(7, "time_to_next", time_diff_col.values)
It's the "insertion index" or the column index where the new column should go. We expect these columns to exist: "time", "rate", "x", "y", "id", "filt_top", "filt_bot". The new column should be added right of "filt _bot" and therefore gets index 7.

2024-07-15 12:47 UTC, luitjansl commented on imod/mf6/model_gwf.py
> +        times: list[datetime],
according to stack overflow, it's the other way around. Importing from the typing library is deprecated. see here: https://stackoverflow.com/questions/24853923/type-hinting-a-collection-of-a-specified-type/62775680#62775680

2024-07-15 14:00 UTC, luitjansl commented on imod/tests/test_mf6/test_mf6_resampling.py
done, moved the testfile to tests/test_mf6/test_utilities/test_resampling.py and removed the tables in it.

2024-07-15 14:20 UTC, luitjansl commented on imod/mf6/simulation.py
> +        times: list[datetime],
issue #1111 was created for this

2024-07-18 13:04 UTC, JoerivanEngelen approved these changes
Looks good! Approved!

2024-07-18 16:00 UTC, merged